# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreerParcoursBTNOnly():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creerParcoursBTNOnly(self):
    self.driver.get("http://localhost/Application/Controller/Accueil/HomePageController.php")
    self.driver.set_window_size(1531, 804)
    self.driver.find_element(By.ID, "navbarDropdownMenuLink").click()
    self.driver.find_element(By.ID, "navbarGererParcours").click()
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("Quiévrechain")
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("NewParcours")
    self.driver.find_element(By.ID, "NombreDechole").click()
    self.driver.find_element(By.ID, "NombreDechole").send_keys("3")
    self.driver.find_element(By.ID, "map").click()
    element = self.driver.find_element(By.ID, "map")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "map")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "map")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "map").click()
    self.driver.find_element(By.ID, "removeLastMarker").click()
    self.driver.find_element(By.ID, "map").click()
    self.driver.find_element(By.ID, "map").click()
    self.driver.find_element(By.ID, "btn-create").click()
    self.driver.close()
  
