# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreerTournoi():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creerTournoi(self):
    self.driver.get("http://localhost/Application/Controller/Accueil/HomePageController.php")
    self.driver.set_window_size(1532, 804)
    self.driver.find_element(By.ID, "navbarDropdownMenuLink").click()
    self.driver.find_element(By.ID, "navbarCreerTournoi").click()
    self.driver.find_element(By.ID, "place").click()
    self.driver.find_element(By.ID, "place").send_keys("Quarouble")
    element = self.driver.find_element(By.ID, "nbParcours")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "nbParcours")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "nbParcours")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "nbParcours").click()
    self.driver.find_element(By.ID, "nbParcours").send_keys("4")
    self.driver.find_element(By.ID, "0").click()
    dropdown = self.driver.find_element(By.ID, "0")
    dropdown.find_element(By.XPATH, "//option[. = 'ikjuyhtr']").click()
    self.driver.find_element(By.ID, "1").click()
    dropdown = self.driver.find_element(By.ID, "1")
    dropdown.find_element(By.XPATH, "//option[. = 'parcoursTest']").click()
    self.driver.find_element(By.ID, "2").click()
    dropdown = self.driver.find_element(By.ID, "2")
    dropdown.find_element(By.XPATH, "//option[. = 'hy']").click()
    self.driver.find_element(By.ID, "3").click()
    dropdown = self.driver.find_element(By.ID, "3")
    dropdown.find_element(By.XPATH, "//option[. = 'NewParcours']").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.close()
  
