# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestModifierUtilisateurAdmin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_modifierUtilisateurAdmin(self):
    self.driver.get("http://4.234.188.41/Application/Controller/Accueil/HomePageController.php")
    self.driver.set_window_size(1532, 804)
    self.driver.find_element(By.ID, "navbarDropdownUtilisateurs").click()
    self.driver.find_element(By.ID, "navbarModifierUtilisateurs").click()
    self.driver.find_element(By.NAME, "editButton").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("Nathan2")
    self.driver.find_element(By.ID, "form").click()
    self.driver.find_element(By.NAME, "lastname").send_keys("LermiX")
    self.driver.find_element(By.ID, "form").click()
    self.driver.find_element(By.NAME, "cotisation").send_keys("1")
    self.driver.find_element(By.ID, "modify").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    self.driver.close()
  
