# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreerEquipeUser():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creerEquipeUser(self):
    self.driver.get("http://4.234.188.41/Application/Controller/Accueil/HomePageController.php")
    self.driver.set_window_size(1527, 804)
    self.driver.find_element(By.ID, "navbarDropdownTournoi").click()
    self.driver.find_element(By.ID, "navbarCreerEquipe").click()
    self.driver.find_element(By.ID, "teamName").click()
    self.driver.find_element(By.ID, "teamName").send_keys("AZER")
    self.driver.find_element(By.ID, "nbMember").click()
    self.driver.find_element(By.ID, "nbMember").send_keys("4")
    self.driver.find_element(By.ID, "0").click()
    dropdown = self.driver.find_element(By.ID, "0")
    dropdown.find_element(By.XPATH, "//option[. = 'LermiX Nathan2']").click()
    self.driver.find_element(By.ID, "1").click()
    dropdown = self.driver.find_element(By.ID, "1")
    dropdown.find_element(By.XPATH, "//option[. = 'Flocon Tristan']").click()
    self.driver.find_element(By.ID, "2").click()
    dropdown = self.driver.find_element(By.ID, "2")
    dropdown.find_element(By.XPATH, "//option[. = 'Gauquier34 Corentin2']").click()
    self.driver.find_element(By.ID, "3").click()
    dropdown = self.driver.find_element(By.ID, "3")
    dropdown.find_element(By.XPATH, "//option[. = 'Carré Ewen']").click()
    self.driver.find_element(By.ID, "submit").click()
    assert self.driver.find_element(By.ID, "swal2-title").text == "Succès !"
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    self.driver.close()
  
