# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestValiderAdhesion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_validerAdhesion(self):
    self.driver.get("http://4.234.188.41/Application/Controller/Accueil/HomePageController.php")
    self.driver.set_window_size(1532, 820)
    self.driver.find_element(By.ID, "Connexion").click()
    self.driver.find_element(By.ID, "mail").click()
    self.driver.find_element(By.ID, "mail").send_keys("corentin.gauquier@gmail.com")
    self.driver.find_element(By.ID, "pwd").send_keys("Aaaaaaa-6")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.LINK_TEXT, "Utilisateurs").click()
    self.driver.find_element(By.LINK_TEXT, "Valider adhésion").click()
    self.driver.find_element(By.ID, "1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    self.driver.find_element(By.ID, "Deconnexion").click()
    self.driver.close()
  
